name: CoVT
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - icu=78.1
  - ld_impl_linux-64=2.45
  - libexpat=2.7.3
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libsqlite=3.51.1
  - libstdcxx=15.2.0
  - libuuid=2.41.3
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.6.0
  - pip=25.3
  - python=3.10.19
  - readline=8.3
  - setuptools=80.9.0
  - tk=8.6.13
  - wheel=0.45.1
  - zstd=1.5.7
  - pip:
      - accelerate==1.12.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.0
      - asttokens==3.0.1
      - async-timeout==5.0.1
      - attrs==25.4.0
      - av==16.0.1
      - brotli==1.2.0
      - cachetools==6.2.4
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==4.4.2
      - decorator==5.2.1
      - dill==0.4.0
      - distro==1.9.0
      - dotenv==0.9.9
      - einops==0.8.1
      - et-xmlfile==2.0.0
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fastapi==0.128.0
      - ffmpy==1.0.0
      - filelock==3.20.1
      - flash-attn==2.7.4.post1
      - fonttools==4.61.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - google-auth==2.45.0
      - google-genai==1.56.0
      - gradio==6.2.0
      - gradio-client==2.0.2
      - groovy==0.1.2
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - imageio==2.37.2
      - ipdb==0.13.13
      - ipython==8.37.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jiter==0.12.0
      - joblib==1.5.3
      - json-repair==0.55.0
      - kiwisolver==1.4.9
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.18
      - networkx==3.4.2
      - nltk==3.9.2
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - omegaconf==2.3.0
      - openai==2.14.0
      - opencv-python==4.12.0.88
      - openpyxl==3.1.5
      - orjson==3.11.5
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==12.0.0
      - portalocker==3.2.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - protobuf==6.33.2
      - psutil==7.2.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==22.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydub==0.25.1
      - pygments==2.19.2
      - pyparsing==3.3.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-multipart==0.0.21
      - pytz==2025.2
      - pyyaml==6.0.3
      - qwen-vl-utils==0.0.14
      - regex==2025.11.3
      - requests==2.32.5
      - rich==14.2.0
      - rsa==4.9.1
      - safehttpx==0.1.7
      - safetensors==0.7.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - semantic-version==2.10.0
      - sentencepiece==0.2.1
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - stack-data==0.6.3
      - starlette==0.50.0
      - sty==1.0.6
      - sympy==1.14.0
      - tabulate==0.9.0
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tiktoken==0.12.0
      - timeout-decorator==0.5.0
      - timm==1.0.22
      - tokenizers==0.22.1
      - tomli==2.3.0
      - tomlkit==0.13.3
      - torch==2.9.1
      - torchvision==0.24.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.57.3
      - triton==3.5.1
      - typer==0.21.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - urllib3==2.6.2
      - uvicorn==0.40.0
      - validators==0.35.0
      - vlmeval==0.1.0
      - wcwidth==0.2.14
      - websockets==15.0.1
      - xlsxwriter==3.2.9
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /rds/general/user/ns1324/home/miniforge3/envs/CoVT
