name: iso
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2025.11.12
  - cmake=4.2.1
  - keyutils=1.6.3
  - krb5=1.21.3
  - ld_impl_linux-64=2.45
  - libblas=3.11.0
  - libcblas=3.11.0
  - libcurl=8.17.0
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.3
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - liblapack=3.11.0
  - liblzma=5.8.1
  - libnghttp2=1.67.0
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libsqlite=3.51.1
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=2.41.2
  - libuv=1.51.0
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - numpy=2.2.6
  - openssl=3.6.0
  - pip=25.3
  - python=3.10.19
  - python_abi=3.10
  - readline=8.3
  - rhash=1.4.6
  - setuptools=80.9.0
  - tk=8.6.13
  - wheel=0.45.1
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - accelerate==1.12.0
      - ag2==0.10.4
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - altair==6.0.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anthropic==0.71.0
      - anyio==4.12.0
      - apache-beam==2.70.0
      - apache-tvm-ffi==0.1.7
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - array-record==0.8.1
      - arrow==1.4.0
      - astor==0.8.1
      - asttokens==3.0.1
      - astunparse==1.6.3
      - async-lru==2.0.5
      - async-timeout==5.0.1
      - attrs==25.4.0
      - autogen==0.10.4
      - av==16.1.0
      - babel==2.17.0
      - beartype==0.21.0
      - beautifulsoup4==4.14.3
      - blake3==1.0.8
      - bleach==6.3.0
      - brotli==1.2.0
      - cachetools==6.2.4
      - cbor2==5.8.0
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpickle==3.1.2
      - comm==0.2.3
      - compressed-tensors==0.12.2
      - contourpy==1.3.2
      - cryptography==46.0.3
      - cuda-bindings==13.1.1
      - cuda-pathfinder==1.3.3
      - cuda-python==13.1.1
      - cupy-cuda12x==13.6.0
      - cycler==0.12.1
      - dashscope==1.25.5
      - debugpy==1.8.19
      - decorator==5.2.1
      - defusedxml==0.7.1
      - depyf==0.20.0
      - dill==0.4.0
      - diskcache==5.6.3
      - distro==1.9.0
      - dm-tree==0.1.9
      - dnspython==2.8.0
      - docker==7.1.0
      - docstring-parser==0.17.0
      - dotenv==0.9.9
      - einops==0.8.1
      - email-validator==2.3.0
      - etils==1.13.0
      - eval-type-backport==0.3.1
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fastapi==0.128.0
      - fastapi-cli==0.0.20
      - fastapi-cloud-cli==0.8.0
      - fastar==0.8.0
      - fastavro==1.12.1
      - fasteners==0.20
      - fastjsonschema==2.21.2
      - fastrlock==0.8.3
      - ffmpy==1.0.0
      - filelock==3.20.1
      - flashinfer-python==0.5.2
      - flatbuffers==25.9.23
      - fonttools==4.61.1
      - fqdn==1.5.1
      - frozenlist==1.8.0
      - fsspec==2025.12.0
      - gast==0.7.0
      - gguf==0.17.1
      - google-pasta==0.2.0
      - gradio==5.38.2
      - gradio-client==1.11.0
      - groovy==0.1.2
      - grpcio==1.65.5
      - h11==0.16.0
      - h5py==3.15.1
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httplib2==0.22.0
      - httptools==0.7.1
      - httpx==0.28.1
      - httpx-sse==0.4.3
      - huggingface-hub==0.36.0
      - idna==3.11
      - immutabledict==4.2.2
      - importlib-resources==6.5.2
      - interegular==0.3.3
      - ipykernel==7.1.0
      - ipython==8.37.0
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - jedi==0.19.2
      - jieba==0.42.1
      - jinja2==3.1.6
      - jiter==0.12.0
      - jmespath==1.0.1
      - json5==0.13.0
      - jsonlines==4.0.0
      - jsonpickle==3.4.2
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-client==8.7.0
      - jupyter-console==6.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.5.1
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - keras==3.12.0
      - kiwisolver==1.4.9
      - lark==1.2.2
      - libclang==18.1.1
      - linkify-it-py==2.0.3
      - llguidance==1.3.0
      - llvmlite==0.44.0
      - lm-format-enforcer==0.11.3
      - loguru==0.7.3
      - lxml==6.0.2
      - markdown==3.10
      - markdown-it-py==2.2.0
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - mcp==1.12.4
      - mdit-py-plugins==0.3.3
      - mdurl==0.1.2
      - mistral-common==1.8.8
      - mistune==3.2.0
      - ml-dtypes==0.5.4
      - model-hosting-container-standards==0.1.12
      - modelscope-studio==1.1.7
      - mpmath==1.3.0
      - msgpack==1.1.2
      - msgspec==0.20.0
      - multidict==6.7.0
      - namex==0.1.0
      - narwhals==2.15.0
      - nbclient==0.10.4
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - ninja==1.13.0
      - notebook==7.5.1
      - notebook-shim==0.2.4
      - numba==0.61.2
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cudnn-frontend==1.17.0
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-cutlass-dsl==4.3.4
      - nvidia-ml-py==13.590.44
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - objsize==0.7.1
      - openai==2.14.0
      - openai-harmony==0.0.8
      - opencv-python-headless==4.12.0.88
      - opt-einsum==3.4.0
      - optree==0.18.0
      - orjson==3.11.5
      - outlines-core==0.2.11
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - parso==0.8.5
      - partial-json-parser==0.2.1.1.post7
      - pdfminer-six==20251107
      - pdfplumber==0.11.8
      - pexpect==4.9.0
      - pillow==11.3.0
      - platformdirs==4.5.1
      - prometheus-client==0.23.1
      - prometheus-fastapi-instrumentator==7.1.0
      - promise==2.3
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - proto-plus==1.27.0
      - protobuf==6.33.2
      - psutil==7.1.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyarrow==18.1.0
      - pyarrow-hotfix==0.7
      - pybase64==1.4.3
      - pycountry==24.6.1
      - pycparser==2.23
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pydantic-extra-types==2.11.0
      - pydantic-settings==2.12.0
      - pydub==0.25.1
      - pygments==2.19.2
      - pymongo==4.15.5
      - pyparsing==3.2.5
      - pypdfium2==5.2.0
      - python-dateutil==2.9.0.post0
      - python-docx==1.2.0
      - python-dotenv==1.2.1
      - python-json-logger==4.0.0
      - python-multipart==0.0.21
      - python-pptx==1.0.2
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - qwen-agent==0.0.31
      - qwen-vl-utils==0.0.14
      - rank-bm25==0.2.2
      - ray==2.53.0
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.2.0
      - rich-toolkit==0.17.1
      - rignore==0.7.6
      - rpds-py==0.30.0
      - ruff==0.14.10
      - safehttpx==0.1.7
      - safetensors==0.7.0
      - scipy==1.15.3
      - seaborn==0.13.2
      - semantic-version==2.10.0
      - send2trash==2.0.0
      - sentencepiece==0.2.1
      - sentry-sdk==2.48.0
      - setproctitle==1.3.7
      - shellingham==1.5.4
      - simple-parsing==0.1.7
      - six==1.17.0
      - sniffio==1.3.1
      - snowballstemmer==3.0.1
      - sortedcontainers==2.4.0
      - soupsieve==2.8.1
      - sse-starlette==3.1.2
      - stack-data==0.6.3
      - starlette==0.50.0
      - supervisor==4.3.0
      - sympy==1.14.0
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - tensorflow-metadata==1.16.1
      - termcolor==3.2.0
      - terminado==0.18.1
      - tfds-nightly==4.9.9.dev202510250044
      - tiktoken==0.12.0
      - tinycss2==1.4.0
      - tokenizers==0.22.1
      - toml==0.10.2
      - tomli==2.3.0
      - tomlkit==0.13.3
      - torch==2.9.0
      - torchaudio==2.9.0
      - torchvision==0.24.0
      - tornado==6.5.4
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.57.3
      - triton==3.5.0
      - typer==0.21.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - uc-micro-py==1.0.3
      - uri-template==1.3.0
      - urllib3==2.6.2
      - uvicorn==0.40.0
      - uvloop==0.22.1
      - vllm==0.11.2
      - watchfiles==1.1.1
      - wcwidth==0.2.14
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - websockets==15.0.1
      - werkzeug==3.1.4
      - widgetsnbextension==4.0.15
      - wrapt==2.0.1
      - xformers==0.0.33.post1
      - xgrammar==0.1.25
      - xlsxwriter==3.2.9
      - yarl==1.22.0
      - zipp==3.23.0
      - zstandard==0.25.0
prefix: /rds/general/user/ns1324/home/miniforge3/envs/iso
