name: sketchpad
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - icu=78.2
  - ld_impl_linux-64=2.45
  - libffi=3.4.6
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnsl=2.0.1
  - libsqlite=3.51.2
  - libstdcxx=15.2.0
  - libuuid=2.41.3
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.6.0
  - pip=25.3
  - python=3.10.0
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.2
  - tk=8.6.13
  - wheel=0.45.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - accelerate==0.23.0
      - addict==2.4.0
      - aiofiles==23.2.1
      - altair==5.5.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.1
      - appdirs==1.4.4
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.1
      - attrs==25.4.0
      - beautifulsoup4==4.14.3
      - black==21.4b2
      - bleach==6.3.0
      - brotli==1.2.0
      - certifi==2026.1.4
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - cityscapesscripts==2.2.2
      - click==8.3.1
      - cloudpickle==3.1.2
      - coloredlogs==15.0.1
      - comm==0.2.3
      - contourpy==1.3.2
      - cycler==0.12.1
      - cython==3.0.2
      - debugpy==1.8.19
      - decorator==5.2.1
      - deepspeed==0.10.3
      - defusedxml==0.7.1
      - detectron2==0.6
      - diffdist==0.1
      - diskcache==5.6.3
      - distro==1.9.0
      - docker==7.1.0
      - docker-pycreds==0.4.0
      - einops==0.7.0
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - fastapi==0.125.0
      - fastjsonschema==2.21.2
      - ffmpy==1.0.0
      - filelock==3.20.3
      - flaml==2.4.1
      - fonttools==4.61.1
      - fqdn==1.5.1
      - fsspec==2026.1.0
      - ftfy==6.1.1
      - future==1.0.0
      - fvcore==0.1.5.post20221221
      - gitdb==4.0.12
      - gitpython==3.1.46
      - gradio==5.38.2
      - gradio-client==1.11.0
      - groovy==0.1.2
      - groundingdino==0.1.0
      - grpcio==1.76.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - hjson==3.1.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - hydra-core==1.3.2
      - idna==3.11
      - imageio==2.37.2
      - importlib-resources==6.5.2
      - infinibatch==0.1.1
      - iopath==0.1.9
      - ipykernel==7.1.0
      - ipython==8.38.0
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.3
      - json-tricks==3.17.3
      - jsonpointer==3.0.0
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.8.0
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-kernel-gateway==3.0.1
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.4
      - jupyterlab-pygments==0.3.0
      - kiwisolver==1.4.9
      - kornia==0.6.8
      - lark==1.3.1
      - lazy-loader==0.4
      - llvmlite==0.46.0
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - mistune==3.2.0
      - more-itertools==10.8.0
      - mpmath==1.3.0
      - multiscaledeformableattention==1.0
      - mup==1.0.0
      - mypy-extensions==1.1.0
      - narwhals==2.15.0
      - nbclient==0.10.4
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - ninja==1.13.0
      - nltk==3.8.1
      - numba==0.63.1
      - numpy==1.23.1
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - openai==1.20.0
      - openai-whisper==20250625
      - opencv-python==4.8.1.78
      - orjson==3.11.5
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.0.3
      - pandocfilters==1.5.1
      - parso==0.8.5
      - pathspec==0.12.1
      - pathtools==0.1.2
      - pexpect==4.9.0
      - pillow==9.4.0
      - platformdirs==4.5.1
      - portalocker==3.2.0
      - prometheus-client==0.24.1
      - prompt-toolkit==3.0.52
      - protobuf==4.25.8
      - psutil==7.2.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyarrow==13.0.0
      - pyautogen==0.2.26
      - pycocotools==2.0.7
      - pycparser==2.23
      - pydantic==2.11.10
      - pydantic-core==2.33.2
      - pydot==4.0.1
      - pydub==0.25.1
      - pygments==2.19.2
      - pyparsing==3.3.1
      - pyquaternion==0.9.9
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-json-logger==4.0.0
      - python-multipart==0.0.21
      - pytz==2025.2
      - pywavelets==1.8.0
      - pyyaml==6.0.1
      - pyzmq==27.1.0
      - referencing==0.37.0
      - regex==2023.10.3
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.2.0
      - rpds-py==0.30.0
      - ruff==0.14.13
      - safehttpx==0.1.7
      - safetensors==0.7.0
      - scikit-image==0.21.0
      - scikit-learn==1.3.1
      - scipy==1.13.1
      - seaborn==0.13.2
      - semantic-sam==1.0
      - semantic-version==2.10.0
      - send2trash==2.1.0
      - sentencepiece==0.1.99
      - sentry-sdk==2.49.0
      - setproctitle==1.3.7
      - shapely==1.8.0
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.8.1
      - stack-data==0.6.3
      - starlette==0.50.0
      - supervision==0.27.0
      - sympy==1.13.1
      - tabulate==0.9.0
      - tenacity==9.1.2
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.3.0
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - tiktoken==0.12.0
      - timm==0.4.12
      - tinycss2==1.4.0
      - tokenizers==0.22.2
      - toml==0.10.2
      - tomli==2.4.0
      - tomlkit==0.13.3
      - torch==2.6.0
      - torchaudio==2.6.0
      - torchvision==0.21.0
      - tornado==6.5.4
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.57.6
      - triton==3.2.0
      - typer==0.21.1
      - typer-slim==0.21.1
      - typing==3.7.4.3
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - uri-template==1.3.0
      - urllib3==2.6.3
      - uvicorn==0.40.0
      - vision-datasets==0.2.2
      - wandb==0.15.12
      - wcwidth==0.2.14
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - websockets==11.0.3
      - werkzeug==3.1.5
      - yacs==0.1.8
      - yapf==0.43.0
prefix: /rds/general/user/ns1324/home/miniforge3/envs/sketchpad
